### Get all users
GET http://localhost:8080/api/users


### Add user
POST http://localhost:8080/api/users/add
Content-Type: application/json

{
  "firstName": "Apple",
  "lastName": "Bees",
  "complexName": "The Complex 7",
  "email": "complex7@yahoo.com",
  "password": "password",
  "phoneNumber": "337-322-1234",
  "address": "1234 Fake St.",
  "city": "Lafayette",
  "state": "LA",
  "zipCode": "70506",
  "country": "USA",
  "latitude": 30.331177413009208,
  "longitude": -92.05008773201289
}


### Save user
POST http://localhost:8080/api/users/save
Content-Type: application/json

{
  "id": 103,
  "firstName": "Joe",
  "lastName": "Dirt",
  "complexName": "The Complex",
  "email": "jbkeelin@fakemail.com",
  "password": "password",
  "phoneNumber": "337-322-1234",
  "address": "1234 Fake St.",
  "city": "Lafayette",
  "state": "LA",
  "zipCode": "70506",
  "country": "USA",
  "latitude": 30.331186413008208,
  "longitude": -92.02008873201288
}

### Get all updates
GET http://localhost:8080/api/updates


### Save update
POST http://localhost:8080/api/updates/save
Content-Type: application/json

{
  "userId": 1,
  "complexName": "Complex 1",
  "date": "2023-06-24",
  "occupancy": 80,
  "prospects": 3,
  "sales": 4,
  "oneBedPrice": 900,
  "twoBedPrice": 1050,
  "threeBedPrice": 1250
}

### Find user
GET http://localhost:8080/api/users/find?email=jbkeelin@fakemail.com&password=password

### Find user
GET https://simplecomplex-production.up.railway.app/api/users/find?email=jbkeelin@fakemail.com&password=password

### Get home
GET http://localhost:8080/api/users/home/1

### Get home
GET https://simplecomplex-production.up.railway.app/api/users/home/1