### Get all users
GET http://localhost:8080/api/main


### Add a user
POST http://localhost:8080/api/main/users
Content-Type: application/json

{
  "id": 3,
  "firstName": "Joe",
  "lastName": "momma",
  "complexName": "The Complex",
  "email": "jbkeelin@fakemail.com",
  "password": "password",
  "phoneNumber": "337-322-9787",
  "address": "1234 Fake St.",
  "city": "Lafayette",
  "state": "LA",
  "zipCode": "70506",
  "country": "USA",
  "xCoordinate": 30.323368393744204,
  "yCoordinate": -92.03026974603779
}